### ISSUE TITLE
Achievement model problem

### ISSUE THREAD

**Issue by moshOntong-IT** [jonafeucht/firebase_game_services#5] opened 2023-01-11 09:54 UTC
Achievement model is not exported in package, I cant import the Achievement Model from this package.

**Comment by jonafeucht** [comment] 2023-01-13 07:10
Hi, could you explain a bit more what the problem is?

**Comment by jonafeucht** [comment] 2023-02-24 14:47
Should be fixed now.
```yaml
firebase_game_services: ^2.0.1
```

**Closed** 2023-02-24 15:38 UTC
